DPR2-2833- test the failure of the script

diff --git a/.github/workflows/generate-test-data.yml b/.github/workflows/generate-test-data.yml
--- a/.github/workflows/generate-test-data.yml
+++ b/.github/workflows/generate-test-data.yml
@@ -50,6 +50,11 @@ jobs:
           
           SQL=$(kotlin ./.github/scripts/GenerateTestData.main.kts) 
           
+          if [[ ! "$SQL" =~ ^BEGIN\; ]]; then
+            echo "::error::Generated SQL script must start with 'BEGIN;'"
+            exit 1
+          fi
+  
           echo "sql<<EOF" >> $GITHUB_OUTPUT
           echo "$SQL" >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT
